SistemaInventario/Areas/Admin/Controllers/BodegaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using SistemaInventario.Data.Repositorio.IRepositorio;
using SistemaInventario.Model;
using SistemaInventario.Utils;

namespace SistemaInventario.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BodegaController : Controller
    {

        private readonly IUnidadTrabajo _unidadTrabajo;

        public BodegaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {

            Bodega bodega = new Bodega();

            if (id == null)
            {
                //se trata de un registro nuevo
                bodega.Estado = true;
                return View(bodega);
            }
            //se trata de una actualizacion a un registro existente
            bodega = await _unidadTrabajo.Bodega.Obtener(id.GetValueOrDefault()); //GetValueOrDefault() permite la recepcion del id nulo
            if (bodega == null)
            {
                //si la bodega no se encontro se retorna notfound
                return NotFound();
            }
            return View(bodega);
        }

        /******
        * creacion y actulizacion de los datos
        */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if (bodega.Id == 0)
                {
                    //verificamos si el nombre de Bodega existe
                    var resultadoJson = await ValidarNombre(bodega.Nombre);
                    var jsonResult = (JsonResult)resultadoJson;                    
                    var jsonData = jsonResult.Value;
                    JObject jsonObject = JObject.FromObject(jsonData);
                    bool existe = (bool)jsonObject["data"];
                    if(existe)
                    {
                        TempData[DS.Error] = "Ya existe una bodega con ese nombre!";
                        return View(bodega);
                    } else {
                        await _unidadTrabajo.Bodega.Adicionar(bodega);
                        //muestra el toast con el mensaje enviado a la TempData de la vista parcial _Notificaiones
                        TempData[DS.Exitosa] = "Bodega creada exitosamente!";
                    }                    
                } else
                {
                    var resultadoJson = await ValidarNombre(bodega.Nombre, bodega.Id);
                    var jsonResult = (JsonResult)resultadoJson;
                    var jsonData = jsonResult.Value;
                    JObject jsonObject = JObject.FromObject(jsonData);
                    bool existe = (bool)jsonObject["data"];
                    if (existe)
                    {
                        TempData[DS.Error] = "Ya existe una bodega con ese nombre!";
                        return View(bodega);
                    }
                    else
                    {
                        _unidadTrabajo.Bodega.Actualizar(bodega);
                        TempData[DS.Exitosa] = "Bodega actualizada exitosamente!";
                    }
                }
                await _unidadTrabajo.Guardar();
                //
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al grabar la Bodega!";
            return View(bodega);
        }


        #region API //metodos que se llaman desde JS

        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Bodega.ObtenerTodos();
            return Json(new { data = todos });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var bodegaDb = await _unidadTrabajo.Bodega.Obtener(id);
            if (bodegaDb == null)
            {
                return Json(new { success = false, message = "Error al eliminar la Bodega"});
            }            
            _unidadTrabajo.Bodega.Eliminar(bodegaDb);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Bodega eliminada exitosamente" });
        }

        //El actionName permite que se pueda llamar con ese nombre este metodo desde JS
        //Este metodo controla que no se tenga una misma bodega con el mismo nombre
        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            var valor = false;
            var listaBodegas = await _unidadTrabajo.Bodega.ObtenerTodos();
            if (id == 0)
            {
                if (nombre != null)
                {
                    valor = listaBodegas.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
                }
            }
            else
            {
                if (nombre != null)
                {
                    //Controla que no se trate del objeto que se esta editando
                    valor = listaBodegas.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
                }
            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }

        #endregion



    }
}

SistemaInventario/Areas/Admin/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using SistemaInventario.Data.Repositorio.IRepositorio;
using SistemaInventario.Model;
using SistemaInventario.Utils;

namespace SistemaInventario.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriaController : Controller
    {

        private readonly IUnidadTrabajo _unidadTrabajo;

        public CategoriaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            //se obtine el registro a modificar o se crea una nueva instancia vacia
            Categoria categoria = new Categoria();

            if (id == null)
            {
                //se trata de un registro nuevo
                categoria.Estado = true;
                return View(categoria);
            }
            //se trata de una actualizacion a un registro existente
            categoria = await _unidadTrabajo.Categoria.Obtener(id.GetValueOrDefault()); //GetValueOrDefault() permite la recepcion del id nulo
            if (categoria == null)
            {
                //si la bodega no se encontro se retorna notfound
                return NotFound();
            }
            return View(categoria);
        }

        /******
        * creacion y actulizacion de los datos
        */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                if (categoria.Id == 0)
                {
                    //verificamos si el nombre de Bodega existe
                    var resultadoJson = await ValidarNombre(categoria.Nombre);
                    var jsonResult = (JsonResult)resultadoJson;                    
                    var jsonData = jsonResult.Value;
                    JObject jsonObject = JObject.FromObject(jsonData);
                    bool existe = (bool)jsonObject["data"];
                    if(existe)
                    {
                        TempData[DS.Error] = "Ya existe una categoria con ese nombre!";
                        return View(categoria);
                    } else {
                        await _unidadTrabajo.Categoria.Adicionar(categoria);
                        //muestra el toast con el mensaje enviado a la TempData de la vista parcial _Notificaiones
                        TempData[DS.Exitosa] = "Categoria creada exitosamente!";
                    }                    
                } else
                {
                    var resultadoJson = await ValidarNombre(categoria.Nombre, categoria.Id);
                    var jsonResult = (JsonResult)resultadoJson;
                    var jsonData = jsonResult.Value;
                    JObject jsonObject = JObject.FromObject(jsonData);
                    bool existe = (bool)jsonObject["data"];
                    if (existe)
                    {
                        TempData[DS.Error] = "Ya existe una categoria con ese nombre!";
                        return View(categoria);
                    }
                    else
                    {
                        _unidadTrabajo.Categoria.Actualizar(categoria);
                        TempData[DS.Exitosa] = "Categoria actualizada exitosamente!";
                    }
                }
                await _unidadTrabajo.Guardar();
                //
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al grabar la Categoria!";
            return View(categoria);
        }


        #region API //metodos que se llaman desde JS

        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Categoria.ObtenerTodos();
            return Json(new { data = todos });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var categoriaDb = await _unidadTrabajo.Categoria.Obtener(id);
            if (categoriaDb == null)
            {
                return Json(new { success = false, message = "Error al eliminar la Categoria"});
            }            
            _unidadTrabajo.Categoria.Eliminar(categoriaDb);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Categoria eliminada exitosamente" });
        }

        //El actionName permite que se pueda llamar con ese nombre este metodo desde JS
        //Este metodo controla que no se tenga una misma bodega con el mismo nombre
        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            var valor = false;
            var listaCategorias = await _unidadTrabajo.Categoria.ObtenerTodos();
            if (id == 0)
            {
                if (nombre != null)
                {
                    valor = listaCategorias.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
                }
            }
            else
            {
                if (nombre != null)
                {
                    //Controla que no se trate del objeto que se esta editando
                    valor = listaCategorias.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
                }
            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }

        #endregion



    }
}

SistemaInventario/Areas/Admin/Controllers/MarcaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using NuGet.Protocol;
using SistemaInventario.Data.Repositorio.IRepositorio;
using SistemaInventario.Model;
using SistemaInventario.Utils;

namespace SistemaInventario.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MarcaController : Controller
    {

        private readonly IUnidadTrabajo _unidadTrabajo;

        public MarcaController(IUnidadTrabajo unidadTrabajo)
        {
            _unidadTrabajo = unidadTrabajo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {

            Marca marca = new Marca();

            if (id == null)
            {
                //se trata de un registro nuevo
                marca.Estado = true;
                return View(marca);
            }
            //se trata de una actualizacion a un registro existente
            marca = await _unidadTrabajo.Marca.Obtener(id.GetValueOrDefault()); //GetValueOrDefault() permite la recepcion del id nulo
            if (marca == null)
            {
                //si la bodega no se encontro se retorna notfound
                return NotFound();
            }
            return View(marca);
        }

        /******
        * creacion y actulizacion de los datos
        */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Marca marca)
        {
            if (ModelState.IsValid)
            {
                if (marca.Id == 0)
                {
                    //verificamos si el nombre de Bodega existe
                    var resultadoJson = await ValidarNombre(marca.Nombre);
                    var jsonResult = (JsonResult)resultadoJson;                    
                    var jsonData = jsonResult.Value;
                    JObject jsonObject = JObject.FromObject(jsonData);
                    bool existe = (bool)jsonObject["data"];
                    if(existe)
                    {
                        TempData[DS.Error] = "Ya existe una marca con ese nombre!";
                        return View(marca);
                    } else {
                        await _unidadTrabajo.Marca.Adicionar(marca);
                        //muestra el toast con el mensaje enviado a la TempData de la vista parcial _Notificaiones
                        TempData[DS.Exitosa] = "Marca creada exitosamente!";
                    }                    
                } else
                {
                    var resultadoJson = await ValidarNombre(marca.Nombre, marca.Id);
                    var jsonResult = (JsonResult)resultadoJson;
                    var jsonData = jsonResult.Value;
                    JObject jsonObject = JObject.FromObject(jsonData);
                    bool existe = (bool)jsonObject["data"];
                    if (existe)
                    {
                        TempData[DS.Error] = "Ya existe una marca con ese nombre!";
                        return View(marca);
                    }
                    else
                    {
                        _unidadTrabajo.Marca.Actualizar(marca);
                        TempData[DS.Exitosa] = "Marca actualizada exitosamente!";
                    }
                }
                await _unidadTrabajo.Guardar();
                //
                return RedirectToAction(nameof(Index));
            }
            TempData[DS.Error] = "Error al grabar la Bodega!";
            return View(marca);
        }


        #region API //metodos que se llaman desde JS

        [HttpGet]
        public async Task<IActionResult> ObtenerTodos()
        {
            var todos = await _unidadTrabajo.Marca.ObtenerTodos();
            return Json(new { data = todos });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var marcaDB = await _unidadTrabajo.Marca.Obtener(id);
            if (marcaDB == null)
            {
                return Json(new { success = false, message = "Error al eliminar la marca"});
            }            
            _unidadTrabajo.Marca.Eliminar(marcaDB);
            await _unidadTrabajo.Guardar();
            return Json(new { success = true, message = "Marca eliminada exitosamente" });
        }

        //El actionName permite que se pueda llamar con ese nombre este metodo desde JS
        //Este metodo controla que no se tenga una misma bodega con el mismo nombre
        [ActionName("ValidarNombre")]
        public async Task<IActionResult> ValidarNombre(string nombre, int id = 0)
        {
            var valor = false;
            var listaMarcas = await _unidadTrabajo.Marca.ObtenerTodos();
            if (id == 0)
            {
                if (nombre != null)
                {
                    valor = listaMarcas.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim());
                }
            }
            else
            {
                if (nombre != null)
                {
                    //Controla que no se trate del objeto que se esta editando
                    valor = listaMarcas.Any(b => b.Nombre.ToLower().Trim() == nombre.ToLower().Trim() && b.Id != id);
                }
            }
            if (valor)
            {
                return Json(new { data = true });
            }
            return Json(new { data = false });
        }

        #endregion



    }
}

SistemaInventario/Views/Shared/_BotonesActualizarYRegresar.cshtml
@model int

<div class="d-grid gap-2 d-md-block">
    <a asp-action="Index" class="btn btn-primary" style="margin-right: 20px"><i class="bi bi-arrow-return-left"></i> Cancelar</a>
    <button type="submit" class="btn btn-success" onfocus="false" asp-route-id="@Model"><i class="bi bi-pencil-fill"></i> Guardar cambios</button>    
</div>

SistemaInventario/Views/Shared/_BotonesCrearYRegresar.cshtml
<div class="d-grid gap-2 d-md-block">
    <a asp-action="Index" class="btn btn-primary" style="margin-right: 20px"><i class="bi bi-arrow-return-left" ></i> Cancelar</a>
    <button type="submit" class="btn btn-success" onfocus="false"><i class="bi bi-plus-square"></i> Crear</button>    
</div>

SistemaInventario/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaInventario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaInventario.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaInventario</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                                Contenido
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Bodega" asp-action="Index">Bodegas</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Categoria" asp-action="Index">Categorías</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Marca" asp-action="Index">Marcas</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Producto" asp-action="Index">Productos</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!-- Aqui se incluye la vista parcial de notificaciones para que este disponible en todas las vistas del proyecto-->
            <partial name="_Notificaciones" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaInventario - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaInventario/Views/Shared/_Notificaciones.cshtml
@using SistemaInventario.Utils

@if (TempData[DS.Exitosa] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[DS.Exitosa]')
    </script>
}

@if (TempData[DS.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[DS.Error]')
    </script>
}